int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
int add(int, int);
void times_table(void);
void print_to_98(int n);
void print_times_table(int n);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void fizzbuzz(void);
void print_triangle(int size);
void print_triangle(int size);
void print_diagonal(int n);
void print_triangle(int size);
void print_triangle(int size);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
char *_strncat(char *dest, char *src, int n);
char *_strcat(char *dest, char *src);
char *rot13(char *);
char *_memset(char *s, char b, unsigned int n);
void set_string(char **s, char *to);
